spring.application.name=demo
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.max-file-size=10MB
logging.level.org.hibernate.orm.jdbc.bind=trace


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.baseline-description=Initial state of existing database
spring.flyway.ignore-migration-patterns=*:future

spring.datasource.hikari.max-lifetime=150000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

app.api.jwk-url=${SUPABASE_JWK_URL}
app.api.hugface-token=${HUGFACE_TOKEN}
app.api.supabase-service-role=${SUPABASE_SERVICE_ROLE}
app.security.api-key.enabled=${SECURITY_API_KEY_ENABLED}
app.security.api-key.value=${SECURITY_API_KEY_VALUE}
app.api.google-api-key=${GOOGLE_API_KEY}
app.api.google-api-url=${GOOGLE_API_URL}
app.api.anime-api-base-url=${ANIME_API_BASE_URL}
app.api.google-title-links-api-key=${GOOGLE_TITLE_LINKS_API_KEY}


app.max-favorite-titles=3


app.sse.timeout-time = 1800000